services:
  open-webui:
    container_name: 'open-webui'
    image: 'ghcr.io/open-webui/open-webui:main'
    volumes:
      - './open-webui:/app/backend/data:rw'
      - './config.yaml:/app/backend/data/litellm/config.yaml:ro'
      - './docs:/data/docs:rw'
    ports:
      - '3003:8080'
    environment:
      DEFAULT_MODELS: 'llama3-70b'
      WEBUI_AUTH: false
    env_file:
      - 'GROQ_API_KEY.env'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: 'unless-stopped'